/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agh;

import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.concurrent.Future;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.log4j.Logger;

/**
 *
 * @author Max
 */
public class MyGUI extends javax.swing.JFrame {

    private ArrayList<Downloader> listDownloaderPool = new ArrayList<Downloader>();
    private DownloaderPool downloaderPool = null;
    private DownloaderWithParseDB parseDownload = null;

    final static Logger logger = Logger.getLogger(MyGUI.class);
    public MyGUI() {
        initComponents();
        bPreview.setEnabled(false);
        
         try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows"/*"Nimbus"*/.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
         }catch(ClassNotFoundException e){
             
         }catch(IllegalAccessException i){
             
         }catch(InstantiationException in){
             
         }catch(UnsupportedLookAndFeelException u){
             
         }
        
        //setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Preferences.loadSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDownload = new javax.swing.JButton();
        bPreview = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        tChannel = new javax.swing.JTabbedPane();
        pToday = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tToday = new javax.swing.JTree();
        pTommorow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTommorow = new javax.swing.JTree();
        pNextDay = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tNextDay = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[JAVA] Artur Kozik");

        bDownload.setText("Download");
        bDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDownloadActionPerformed(evt);
            }
        });

        bPreview.setText("Preview");
        bPreview.setMaximumSize(new java.awt.Dimension(79, 23));
        bPreview.setMinimumSize(new java.awt.Dimension(79, 23));
        bPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPreviewActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(tToday);

        javax.swing.GroupLayout pTodayLayout = new javax.swing.GroupLayout(pToday);
        pToday.setLayout(pTodayLayout);
        pTodayLayout.setHorizontalGroup(
            pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        pTodayLayout.setVerticalGroup(
            pTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        tChannel.addTab("Today", pToday);

        jScrollPane1.setViewportView(tTommorow);

        javax.swing.GroupLayout pTommorowLayout = new javax.swing.GroupLayout(pTommorow);
        pTommorow.setLayout(pTommorowLayout);
        pTommorowLayout.setHorizontalGroup(
            pTommorowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        pTommorowLayout.setVerticalGroup(
            pTommorowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        tChannel.addTab("Tommorow", pTommorow);

        jScrollPane2.setViewportView(tNextDay);

        javax.swing.GroupLayout pNextDayLayout = new javax.swing.GroupLayout(pNextDay);
        pNextDay.setLayout(pNextDayLayout);
        pNextDayLayout.setHorizontalGroup(
            pNextDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        pNextDayLayout.setVerticalGroup(
            pNextDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        tChannel.addTab("Next day", pNextDay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(bPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tChannel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tChannel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDownloadActionPerformed
        
        parseDownload = new DownloaderWithParseDB(Preferences.prefList.get(0));
        
        listDownloaderPool.add(parseDownload);
  
        downloaderPool = new DownloaderPool();		
        try {
                ArrayList<Future<?>> tasks = downloaderPool.addAll(listDownloaderPool);
        } catch (MalformedURLException e1) {
                logger.error("Natrafiono na konflikt podczas próby pobierania plików.");
                e1.printStackTrace();
        }
        
        listDownloaderPool.clear();
    }//GEN-LAST:event_bDownloadActionPerformed

    private void bPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPreviewActionPerformed

        
    }//GEN-LAST:event_bPreviewActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        logger.info("Aplikacja została zamkniêta.");
        System.exit(NORMAL);
    }//GEN-LAST:event_bExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bDownload;
    private javax.swing.JButton bExit;
    public static javax.swing.JButton bPreview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPanel pNextDay;
    private javax.swing.JPanel pToday;
    private javax.swing.JPanel pTommorow;
    private javax.swing.JTabbedPane tChannel;
    private javax.swing.JTree tNextDay;
    private javax.swing.JTree tToday;
    private javax.swing.JTree tTommorow;
    // End of variables declaration//GEN-END:variables
}
